"""debug DB

Revision ID: 2d54db3c951c
Revises: c014b16f3ecb
Create Date: 2024-04-15 22:24:43.324926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d54db3c951c'
down_revision: Union[str, None] = 'c014b16f3ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_image', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('item_image', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('item_image', sa.Column('mimetype', sa.String(length=255), nullable=False))
    op.add_column('item_image', sa.Column('original', sa.Boolean(), nullable=False))
    op.add_column('item_image', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_image', 'created_at')
    op.drop_column('item_image', 'original')
    op.drop_column('item_image', 'mimetype')
    op.drop_column('item_image', 'height')
    op.drop_column('item_image', 'width')
    # ### end Alembic commands ###
