"""add class ItemImage

Revision ID: c014b16f3ecb
Revises: 3eb87c0eeb7e
Create Date: 2024-04-15 22:18:07.241635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c014b16f3ecb'
down_revision: Union[str, None] = '3eb87c0eeb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_image',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.drop_column('item', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('item_image')
    # ### end Alembic commands ###
